#!/bin/bash
# MyApp
#
# description: bla bla

case $1 in
    start)
        /bin/bash /home/vagrant/Downloads/ltsa.sh
    ;;
    restart)
        /bin/bash /home/vagrant/Downloads/ltsa.sh
    ;;
esac
exit 0
