# -*- mode: ruby -*-
# vi: set ft=ruby :

#__author__ = "Sattwik Pati aka ICE!V!an"
#__copyright__ = "NA"
#__license__ = "NA"
#__version__ = "NA"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Vagrant Box being used
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  #Display settings
   config.vm.provider "virtualbox" do |vb|
   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
     # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  #Provisions to be added to the VM
  config.vm.provision "shell", inline: <<-SHELL
    #Command to remove desktop Lock
    gsettings set org.gnome.desktop.screensaver lock-enabled false
    #Command to add java repo
    add-apt-repository ppa:webupd8team/java
    #Update Command 
    apt-get update -qq
    echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
    #Java 8 installation
    apt-get install --yes oracle-java8-installer
    yes "" | apt-get -f install
    #LTSA-PCA tool download
    sudo wget -O /home/vagrant/Desktop/LTSA-PCA.jar "https://dl.dropboxusercontent.com/u/996431/software/ltsa-pca/LTSA-PCA.jar"
    sudo wget -O /home/vagrant/Desktop/examples.zip "https://dl.dropboxusercontent.com/u/996431/software/ltsa-pca/examples.zip"
    mkdir /home/vagrant/Desktop/examples
    unzip /home/vagrant/Desktop/examples.zip -d /home/vagrant/Desktop/examples1
    mv /home/vagrant/Desktop/examples1/examples /home/vagrant/Desktop
    rm -rf /home/vagrant/Desktop/examples1
    SHELL
end
