# -*- mode: ruby -*-
# vi: set ft=ruby :

#__author__ = "Sattwik Pati aka ICE!V!an"
#__copyright__ = "NA"
#__license__ = "NA"
#__version__ = "NA"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
     # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    #Command to remove desktop Lock
    gsettings set org.gnome.desktop.screensaver lock-enabled false
    #Command to add java repo
    add-apt-repository ppa:webupd8team/java
    #Update Command 
    apt-get update -qq
    echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
    #Java 8 installation
    apt-get install --yes oracle-java8-installer
    yes "" | apt-get -f install
    #LTSA-PCA tool download
    sudo wget -O /home/vagrant/Desktop/LTSA-PCA.jar "https://dl.dropboxusercontent.com/u/996431/software/ltsa-pca/LTSA-PCA.jar"
    sudo wget -O /home/vagrant/Desktop/examples.zip "https://dl.dropboxusercontent.com/u/996431/software/ltsa-pca/examples.zip"
    mkdir /home/vagrant/Desktop/examples
    unzip /home/vagrant/Desktop/examples.zip -d /home/vagrant/Desktop/examples1
    mv /home/vagrant/Desktop/examples1/examples /home/vagrant/Desktop
    rm -rf /home/vagrant/Desktop/examples1
    SHELL
  #config.vm.provision :shell, :inline => "sudo apt-get -y update"
  #config.vm.provision :shell, :inline => "sudo apt-get -y install openjdk-7-jre"
  #config.vm.provision :shell, :inline => 'sudo wget -O /home/vagrant/Desktop/LTSA-PCA.jar "https://dl.dropboxusercontent.com/u/996431/software/ltsa-pca/LTSA-PCA.jar"'
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
